### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [tallKitties/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tallKitties** [comment]
Thanks for the feedback Ken! I made the changes and updated my github repo & heroku.

I did run into something while doing that though: I set the meta viewport tag and it worked for the most part. However, it seemed to "auto-zoom" when I rotated my iPhone to horizontal.

After doing some more research, I found that just setting the initial-scale to 1 and leaving out the "width=device-width" all-together, along with setting the @viewport tag in CSS, seemed to take care of the "auto-zooming" issue when rotating my phone.

Am I headed in the right direction?

**Comment by kenmazaika** [comment]
There are a few different ways you can configure the application to work.  Your initial solution https://github.com/tallKitties/splurty/commit/08bc3cc189931226d2b36d9a3663d51d27c9874f is the solution I would implement if I were building it, but depending on how you want it setup you can use different settings in cases like rotating like you've pointed out.

Thumbs up!  You're definitely on the right track!!

**Comment by tallKitties** [comment]
Ah, OK I'll keep that in mind for the future. Thanks!
